import type { BibleBook } from '../types';

export const BIBLE_BOOKS: BibleBook[] = [
  { name: 'Genesis', testament: 'old', description: 'The book of beginnings' },
  { name: 'Exodus', testament: 'old', description: 'The departure from Egypt' },
  { name: 'Leviticus', testament: 'old', description: 'Laws for worship and living' },
  { name: 'Numbers', testament: 'old', description: 'The census and wanderings' },
  { name: 'Deuteronomy', testament: 'old', description: 'The second law and covenant' },
  { name: 'Joshua', testament: 'old', description: 'Conquest of the Promised Land' },
  { name: 'Judges', testament: 'old', description: 'Israel’s cycle of sin and deliverance' },
  { name: 'Ruth', testament: 'old', description: 'The story of loyalty and redemption' },
  { name: '1 Samuel', testament: 'old', description: 'The rise of Samuel and Saul' },
  { name: '2 Samuel', testament: 'old', description: 'The reign of King David' },
  { name: '1 Kings', testament: 'old', description: 'The reign of Solomon and the divided kingdom' },
  { name: '2 Kings', testament: 'old', description: 'The history of the divided kingdom' },
  { name: '1 Chronicles', testament: 'old', description: 'Genealogies and the reign of David' },
  { name: '2 Chronicles', testament: 'old', description: 'The history of Judah and the temple' },
  { name: 'Ezra', testament: 'old', description: 'Return from exile and rebuilding' },
  { name: 'Nehemiah', testament: 'old', description: 'Rebuilding the walls of Jerusalem' },
  { name: 'Esther', testament: 'old', description: 'The story of a Jewish queen in Persia' },
  { name: 'Job', testament: 'old', description: 'The story of suffering and faith' },
  { name: 'Psalms', testament: 'old', description: 'Book of prayers and praise' },
  { name: 'Proverbs', testament: 'old', description: 'Wisdom literature and sayings' },
  { name: 'Ecclesiastes', testament: 'old', description: 'Reflections on the meaning of life' },
  { name: 'Song of Solomon', testament: 'old', description: 'A poetic love song' },
  { name: 'Isaiah', testament: 'old', description: 'Major prophet with messages of hope' },
  { name: 'Jeremiah', testament: 'old', description: 'Prophecies of judgment and restoration' },
  { name: 'Lamentations', testament: 'old', description: 'Poems of mourning over Jerusalem' },
  { name: 'Ezekiel', testament: 'old', description: 'Visions and prophecies during exile' },
  { name: 'Daniel', testament: 'old', description: 'Stories and visions in Babylon' },
  { name: 'Hosea', testament: 'old', description: 'Prophet of God’s love and judgment' },
  { name: 'Joel', testament: 'old', description: 'Prophecy of the Day of the Lord' },
  { name: 'Amos', testament: 'old', description: 'Messages of justice and righteousness' },
  { name: 'Obadiah', testament: 'old', description: 'Prophecy against Edom' },
  { name: 'Jonah', testament: 'old', description: 'The reluctant prophet to Nineveh' },
  { name: 'Micah', testament: 'old', description: 'Prophecies of judgment and hope' },
  { name: 'Nahum', testament: 'old', description: 'Prophecy against Nineveh' },
  { name: 'Habakkuk', testament: 'old', description: 'Questions about God’s justice' },
  { name: 'Zephaniah', testament: 'old', description: 'Prophecies of judgment and restoration' },
  { name: 'Haggai', testament: 'old', description: 'Encouragement to rebuild the temple' },
  { name: 'Zechariah', testament: 'old', description: 'Visions and prophecies of hope' },
  { name: 'Malachi', testament: 'old', description: 'Final prophet before the New Testament' },
  { name: 'Matthew', testament: 'new', description: 'The first Gospel' },
  { name: 'Mark', testament: 'new', description: 'The Gospel of action and immediacy' },
  { name: 'Luke', testament: 'new', description: 'The Gospel of compassion and detail' },
  { name: 'John', testament: 'new', description: 'The Gospel of love and divinity' },
  { name: 'Acts', testament: 'new', description: 'The early church and the spread of the Gospel' },
  { name: 'Romans', testament: 'new', description: 'Paul\'s letter to Rome' },
  { name: '1 Corinthians', testament: 'new', description: 'Addressing issues in the church' },
  { name: '2 Corinthians', testament: 'new', description: 'Paul’s defense of his apostleship' },
  { name: 'Galatians', testament: 'new', description: 'Freedom in Christ and the Gospel' },
  { name: 'Ephesians', testament: 'new', description: 'The church as the body of Christ' },
  { name: 'Philippians', testament: 'new', description: 'Joy in Christ and encouragement' },
  { name: 'Colossians', testament: 'new', description: 'The supremacy of Christ' },
  { name: '1 Thessalonians', testament: 'new', description: 'Encouragement in faith and hope' },
  { name: '2 Thessalonians', testament: 'new', description: 'Clarification on the Day of the Lord' },
  { name: '1 Timothy', testament: 'new', description: 'Instructions for church leadership' },
  { name: '2 Timothy', testament: 'new', description: 'Paul’s final letter of encouragement' },
  { name: 'Titus', testament: 'new', description: 'Guidance for church leaders' },
  { name: 'Philemon', testament: 'new', description: 'A plea for a runaway slave' },
  { name: 'Hebrews', testament: 'new', description: 'The superiority of Christ' },
  { name: 'James', testament: 'new', description: 'Faith in action and practical wisdom' },
  { name: '1 Peter', testament: 'new', description: 'Encouragement in suffering' },
  { name: '2 Peter', testament: 'new', description: 'Warnings against false teachers' },
  { name: '1 John', testament: 'new', description: 'Love and assurance in faith' },
  { name: '2 John', testament: 'new', description: 'A warning against false teachers' },
  { name: '3 John', testament: 'new', description: 'Commendation of hospitality' },
  { name: 'Jude', testament: 'new', description: 'A call to contend for the faith' },
  { name: 'Revelation', testament: 'new', description: 'Visions of the end times and Christ’s return' }
];